[package]
name = "ascii"
version = "0.1.0"
authors = ["AndyTheGiant <andy.bialystock@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }
